# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  session:
    handler_id: null
    cookie_lifetime: 3600 # Durée de vie du cookie de session (en secondes)
    save_path: "%kernel.cache_dir%/sessions" # Où stocker les sessions sur le serveur
    cookie_secure: auto # Activé en production pour sécuriser le cookie
    cookie_samesite: "lax" # Valeur correcte : 'lax', 'strict', ou 'none'
when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
